<div class="header">
    <img src="https://sun9-56.userapi.com/impg/9Z-S3ieQHUutk4epPPKMGGt4h2ywXqRrmVyHTQ/NFNCRrYIJ7I.jpg?size=1907x727&quality=96&sign=529f34a1e1cd41e08441c9eaeab102d9&type=album" alt="Логотип компании">
    <div>
        <button type="button">
            <a href="/sign-in">Вход</a></button>
        <button type="button">
            <a href="/sign-up">Регистрация</a></button>
    </div>
</div>